//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SZI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public System.Guid AddressId { get; set; }
        public int HouseNo { get; set; }
        public Nullable<int> FlatNo { get; set; }
        public System.Guid AreaId { get; set; }
    }
}
