//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SZI
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Data.Entity.Infrastructure;

    /// <summary>
    /// Wygenerowana uatomatycznie klasa - odpowiednik tabeli Licznik.
    /// </summary>
    public partial class Counter : IItem
    {
        /// <summary>
        /// Nuumer licznika.
        /// </summary>
        public int CounterNo { get; set; }
        /// <summary>
        /// Numer uk³adu.
        /// </summary>
        public int CircuitNo { get; set; }
        /// <summary>
        /// Id adresu.
        /// </summary>
        public Nullable<System.Guid> AddressId { get; set; }
        /// <summary>
        /// Id klienta.
        /// </summary>
        public string CustomerId { get; set; }

        /// <summary>
        /// Pobranie elementu w formie tablicy string.
        /// </summary>
        public string[] GetElements
        {
            get
            {
                return new string[]{
                    CounterNo.ToString(),
                    CircuitNo.ToString(),
                    AddressId.ToString(),
                    CustomerId
                };
            }
        }

        /// <summary>
        /// Dodaje rekord do tabeli.
        /// </summary>
        public void InsertIntoDB()
        {
            try
            {
                using (var database = new CollectorsManagementSystemEntities())
                {
                    database.Counters.Add(this);
                    database.SaveChanges();
                }
            }
            catch (DbUpdateException ex)
            {
                var innerEx = ex.InnerException;

                while (innerEx.InnerException != null)
                    innerEx = innerEx.InnerException;

                System.Windows.Forms.MessageBox.Show(innerEx.Message);
            }
        }

        /// <summary>
        /// Modyfikuje odpowiedni rekord.
        /// </summary>
        /// <param name="id">Id modyfikowanego rekordu.</param>
        public void ModifyRecord(string id)
        {
            using (var dataBase = new CollectorsManagementSystemEntities())
            {
                dataBase.Database.ExecuteSqlCommand
                (
                    "UPDATE Counter SET CircuitNo={0}, AddressId={1}, CustomerId={2} WHERE CounterNo={3}",
                    this.CircuitNo,
                    this.AddressId,
                    this.CustomerId,
                    id
                );
                dataBase.SaveChanges();
            }
        }
    }
}
