//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SZI
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Data.Entity.Infrastructure;
    using System.Text.RegularExpressions;

    /// <summary>
    /// Wygenerowana automatycznie klasa - odpowiednik tabeli Klient.
    /// </summary>
    public partial class Customer : IItem
    {
        /// <summary>
        /// Id klienta.
        /// </summary>
        public string CustomerId { get; set; }
        /// <summary>
        /// Imiê.
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// Nazwisko.
        /// </summary>
        public string LastName { get; set; }
        /// <summary>
        /// Kod pocztowy.
        /// </summary>
        public string PostalCode { get; set; }
        /// <summary>
        /// Miasto.
        /// </summary>
        public string City { get; set; }
        /// <summary>
        /// Adres.
        /// </summary>
        public string Address { get; set; }
        /// <summary>
        /// Telefon kontaktowy.
        /// </summary>
        public string PhoneNumber { get; set; }

        public string[] GetElements
        {
            get
            {
                return new string[]
                {
                    CustomerId,
                    Name,
                    LastName,
                    PostalCode,
                    City,
                    Address,
                    PhoneNumber
                };
            }
        }

        /// <summary>
        /// Dodaje rekord do tabeli.
        /// </summary>
        public void InsertIntoDB()
        {
            try
            {
                using (var database = new CollectorsManagementSystemEntities())
                {
                    this.PostalCode = Regex.Replace(this.PostalCode, "-", "");
                    database.Customers.Add(this);
                    database.SaveChanges();
                }
            }
            catch (DbUpdateException Ex)
            {
                ExceptionHandling.ShowException(Ex);
            }
        }

        /// <summary>
        /// Modyfikuje odpowiedni rekord.
        /// </summary>
        /// <param name="id">Id modyfikowanego rekordu.</param>
        public void ModifyRecord(string id)
        {
            using (var dataBase = new CollectorsManagementSystemEntities())
            {
                dataBase.Database.ExecuteSqlCommand
                (
                    "UPDATE Customer SET Name={0}, LastName={1}, PostalCode={2}, City={3}, Address={4}, PhoneNumber={5} WHERE CustomerId={6}",
                    this.Name,
                    this.LastName,
                    Regex.Replace(this.PostalCode, "-", ""),
                    this.City,
                    this.Address,
                    this.PhoneNumber,
                    id
                );
                dataBase.SaveChanges();
            }
        }
    }
}
