

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SZI
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class CollectorsManagementSystemEntities : DbContext
{
    public CollectorsManagementSystemEntities()
        : base("name=CollectorsManagementSystemEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<Address> Addresses { get; set; }

    public DbSet<Area> Areas { get; set; }

    public DbSet<Collector> Collectors { get; set; }

    public DbSet<Counter> Counters { get; set; }

    public DbSet<Customer> Customers { get; set; }

    public DbSet<Reading> Readings { get; set; }

}

}

