
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SZI
{

    using System;
    using System.Collections.Generic;
    using System.Data.Entity.Infrastructure;
    
    public partial class Reading
    {
        public System.Guid ReadingId { get; set; }
        public System.DateTime Date { get; set; }
        public double Value { get; set; }
        public string CollectorId { get; set; }
        public int CounterNo { get; set; }

        public void InsertIntoDB()
        {
            try
            {
                using (var database = new CollectorsManagementSystemEntities())
                {
                    database.Readings.Add(this);
                    database.SaveChanges();
                }
            }
            catch (DbUpdateException ex)
            {
                ExceptionHandling.ShowException(ex);
            }
        }
    }

}
