
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SZI
{

    using System;
    using System.Collections.Generic;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Validation;
    using System.Windows.Forms;
    using System.Linq;

    /// <summary>
    /// Klasa pozwalające na obsługę tabeli odczyty.
    /// </summary>
    public partial class Reading
    {
        /// <summary>
        /// Klucz główny tabeli odczyty - unikatowe wartości.
        /// </summary>
        public System.Guid ReadingId { get; set; }
        /// <summary>
        /// Data dodania odczytu do bazy danych.
        /// </summary>
        public System.DateTime Date { get; set; }
        /// <summary>
        /// Wartość odczytu.
        /// </summary>
        public double Value { get; set; }
        /// <summary>
        /// Inkasent, który wykonał dany odczyt.
        /// </summary>
        public string CollectorId { get; set; }
        /// <summary>
        /// Numer licznika dla którego został wykonany odczyt.
        /// </summary>
        public int CounterNo { get; set; }

        /// <summary>
        /// Funkcja pozwalająca dodać nowy rekord do bazy danych.
        /// </summary>
        public void InsertIntoDB()
        {
            try
            {
                using (var database = new CollectorsManagementSystemEntities())
                {
                    database.Readings.Add(this);
                    database.SaveChanges();
                }
            }
            catch (DbEntityValidationException ex)
            {
                var errorMessages = String.Empty;

                foreach (var validationResult in ex.EntityValidationErrors)
                {
                    string entityName = validationResult.Entry.Entity.GetType().Name;
                    foreach (DbValidationError error in validationResult.ValidationErrors)
                    {
                        errorMessages += entityName + "." + error.PropertyName + ": " + error.ErrorMessage + "\n";
                    }
                }
                MessageBox.Show(errorMessages);
            }
            catch (DbUpdateException ex)
            {
                ExceptionHandling.ShowException(ex);
            }
        }

        /// <summary>
        /// Funkcja pozwalająca na aktualizację rekordu w bazie danych.
        /// </summary>
        /// <returns>Informacja o poprawnoťci dodania rekordu.</returns>
        public bool UpdateDB()
        {
            try
            {
                using (var dataBase = new CollectorsManagementSystemEntities())
                {
                    var items = from reading in dataBase.Readings
                                where reading.ReadingId == this.ReadingId
                                select reading;

                    foreach (var item in items)
                    {
                        item.Value = this.Value;
                        item.CollectorId = this.CollectorId;
                    }

                    dataBase.SaveChanges();
                }
                return true;
            }
            catch (DbUpdateException ex)
            {
                ExceptionHandling.ShowException(ex);
                return false;
            }
        }
    }

}
